import {
  Document, Page, Text, View, StyleSheet, Font, Image, pdf,
} from '@react-pdf/renderer'
import type { DailyFleetAttendanceReport } from '@/types'
import ferosLogo from '@/assets/feros_transperant_logo.png'

Font.register({
  family: 'NotoSans',
  fonts: [
    { src: '/NotoSans-Regular.ttf', fontWeight: 'normal' },
    { src: '/NotoSans-Bold.ttf',    fontWeight: 'bold'   },
  ],
})

const NAVY = '#1E3A5F'

const S = StyleSheet.create({
  page: {
    fontFamily: 'NotoSans',
    fontSize: 8,
    color: '#000',
    backgroundColor: '#fff',
    padding: 20,
  },
  watermark: {
    position: 'absolute',
    top: '30%',
    left: '20%',
    width: 280,
    opacity: 0.06,
  },
  header: { marginBottom: 8 },
  title: { fontSize: 13, fontWeight: 'bold', color: NAVY, textAlign: 'center' },
  subtitle: { fontSize: 9, textAlign: 'center', color: '#555', marginTop: 2 },
  divider: { borderBottom: `1.5pt solid ${NAVY}`, marginVertical: 6 },
  statsRow: { flexDirection: 'row', justifyContent: 'center', gap: 16, marginBottom: 10 },
  statBox: {
    border: `1pt solid ${NAVY}`, borderRadius: 3, padding: '4 10',
    alignItems: 'center', minWidth: 70,
  },
  statLabel: { fontSize: 6.5, color: '#555', textTransform: 'uppercase' },
  statValue: { fontSize: 12, fontWeight: 'bold', color: NAVY, marginTop: 1 },
  tableHeader: { flexDirection: 'row', backgroundColor: NAVY, padding: '4 0' },
  tableRow: { flexDirection: 'row', borderBottom: '0.5pt solid #ddd', padding: '3 0' },
  tableRowAlt: { flexDirection: 'row', backgroundColor: '#F8FAFC', borderBottom: '0.5pt solid #ddd', padding: '3 0' },
  cell: { paddingHorizontal: 4, fontSize: 7.5 },
  hCell: { paddingHorizontal: 4, fontSize: 7.5, fontWeight: 'bold', color: '#fff' },
  colNo:      { width: '6%' },
  colVehicle: { width: '18%' },
  colScope:   { width: '14%' },
  colType:    { width: '20%' },
  colDriver:  { width: '21%' },
  colCleaner: { width: '21%' },
  dash: { color: '#aaa' },
  footer: { marginTop: 8, fontSize: 6.5, color: '#aaa', textAlign: 'right' },
})

function StatBox({ label, value }: { label: string; value: number }) {
  return (
    <View style={S.statBox}>
      <Text style={S.statLabel}>{label}</Text>
      <Text style={S.statValue}>{value}</Text>
    </View>
  )
}

const formatDate = (iso: string) => {
  const [y, m, d] = iso.split('-')
  return `${d}-${m}-${y}`
}

type Props = { report: DailyFleetAttendanceReport; tenantName?: string }

function FleetAttendanceDoc({ report, tenantName }: Props) {
  return (
    <Document>
      <Page size="A4" style={S.page}>
        <Image src={ferosLogo} style={S.watermark} />

        <View style={S.header}>
          <Text style={S.title}>
            Daily Fleet Staff Attendance Report — {report.scope}
          </Text>
          <Text style={S.subtitle}>
            {tenantName ? `${tenantName}  |  ` : ''}Date: {formatDate(report.date)}
          </Text>
        </View>

        <View style={S.divider} />

        <View style={S.statsRow}>
          <StatBox label="Total Vehicles" value={report.totalVehicles} />
          <StatBox label="Drivers"        value={report.drivers} />
          <StatBox label="Cleaners"       value={report.cleaners} />
          <StatBox label="Unassigned"     value={report.unassigned} />
        </View>

        {/* Table header */}
        <View style={S.tableHeader}>
          <Text style={[S.hCell, S.colNo]}>#</Text>
          <Text style={[S.hCell, S.colVehicle]}>Vehicle No.</Text>
          <Text style={[S.hCell, S.colScope]}>Scope</Text>
          <Text style={[S.hCell, S.colType]}>Type</Text>
          <Text style={[S.hCell, S.colDriver]}>Driver</Text>
          <Text style={[S.hCell, S.colCleaner]}>Cleaner</Text>
        </View>

        {report.rows.map((row, i) => (
          <View key={i} style={i % 2 === 0 ? S.tableRow : S.tableRowAlt}>
            <Text style={[S.cell, S.colNo]}>{i + 1}</Text>
            <Text style={[S.cell, S.colVehicle]}>{row.registrationNumber}</Text>
            <Text style={[S.cell, S.colScope]}>{row.scope}</Text>
            <Text style={[S.cell, S.colType]}>{row.vehicleType}</Text>
            <Text style={[S.cell, S.colDriver, row.driverName === '—' ? S.dash : {}]}>{row.driverName}</Text>
            <Text style={[S.cell, S.colCleaner, row.cleanerName === '—' ? S.dash : {}]}>{row.cleanerName}</Text>
          </View>
        ))}

        <Text style={S.footer}>Generated by FEROS</Text>
      </Page>
    </Document>
  )
}

export async function downloadDailyFleetAttendancePdf(
  report: DailyFleetAttendanceReport,
  tenantName?: string,
) {
  const blob = await pdf(<FleetAttendanceDoc report={report} tenantName={tenantName} />).toBlob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `fleet-attendance-${report.scope.replace(' ', '-').toLowerCase()}-${report.date}.pdf`
  a.click()
  URL.revokeObjectURL(url)
}
